const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store",...h}});
const enc=new TextEncoder();const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");async function sha(s){return hex(await crypto.subtle.digest("SHA-256",enc.encode(s)))}async function pass(p,s){const key=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);return hex(await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(s),iterations:210000,hash:"SHA-256"},key,256))}function cookie(req,n){return req.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(n+"="))?.slice(n.length+1)||null}async function user(req,env){const t=cookie(req,"anidex_session");if(!t)return null;return env.DB.prepare("SELECT u.id,u.email,u.display_name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')").bind(await sha(t)).first()}async function session(uid,env){const t=crypto.randomUUID()+crypto.randomUUID(),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").bind(await sha(t),uid,exp).run();return `anidex_session=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`}
export default{async fetch(req,env){const u=new URL(req.url);if(!u.pathname.startsWith("/api/")&&!u.pathname.startsWith("/media/"))return env.ASSETS.fetch(req);try{
if(u.pathname==="/api/health")return J({ok:true,app:"AniDex",version:"2.1.0"});
if(u.pathname==="/api/auth/register"&&req.method==="POST"){const b=await req.json(),email=(b.email||"").trim().toLowerCase(),name=(b.displayName||"").trim();if(!email.includes("@")||name.length<2||(b.password||"").length<8)return J({error:"Controleer naam, e-mail en wachtwoord (minimaal 8 tekens)."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return J({error:"Er bestaat al een account met dit e-mailadres."},409);const id=crypto.randomUUID(),salt=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,email,display_name,password_hash,password_salt) VALUES(?,?,?,?,?)").bind(id,email,name,await pass(b.password,salt),salt).run();return J({ok:true,user:{id,email,displayName:name}},201,{"set-cookie":await session(id,env)})}
if(u.pathname==="/api/auth/login"&&req.method==="POST"){const b=await req.json(),row=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind((b.email||"").trim().toLowerCase()).first();if(!row||await pass(b.password||"",row.password_salt)!==row.password_hash)return J({error:"E-mailadres of wachtwoord klopt niet."},401);return J({ok:true,user:{id:row.id,email:row.email,displayName:row.display_name}},200,{"set-cookie":await session(row.id,env)})}
if(u.pathname==="/api/auth/logout"&&req.method==="POST"){const t=cookie(req,"anidex_session");if(t)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha(t)).run();return J({ok:true},200,{"set-cookie":"anidex_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"})}
if(u.pathname==="/api/auth/me"){const me=await user(req,env);return me?J({user:{id:me.id,email:me.email,displayName:me.display_name}}):J({error:"Niet ingelogd"},401)}
if(u.pathname.startsWith("/media/")&&req.method==="GET"){const me=await user(req,env);if(!me)return J({error:"Niet ingelogd"},401);const key=decodeURIComponent(u.pathname.slice(7));if(!key.startsWith(me.id+"/"))return J({error:"Geen toegang"},403);const obj=await env.PHOTOS.get(key);if(!obj)return new Response("Not found",{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set("etag",obj.httpEtag);h.set("cache-control","private,max-age=3600");return new Response(obj.body,{headers:h})}
if(u.pathname==="/api/sightings"&&req.method==="GET"){const me=await user(req,env);if(!me)return J({error:"Niet ingelogd"},401);const {results}=await env.DB.prepare("SELECT * FROM sightings WHERE user_id=? ORDER BY created_at DESC").bind(me.id).all();return J({sightings:results.map(x=>({...x,photoUrl:x.photo_key?"/media/"+encodeURIComponent(x.photo_key):null}))})}
if(u.pathname==="/api/sightings"&&req.method==="POST"){const me=await user(req,env);if(!me)return J({error:"Niet ingelogd"},401);const b=await req.json();if(!b.species)return J({error:"Onvolledige waarneming"},400);let key=null;if(b.image){const m=/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/.exec(b.image);if(!m)return J({error:"Ongeldige afbeelding"},400);const bytes=Uint8Array.from(atob(m[2]),c=>c.charCodeAt(0));key=`${me.id}/${crypto.randomUUID()}.jpg`;await env.PHOTOS.put(key,bytes,{httpMetadata:{contentType:m[1]}})}const r=await env.DB.prepare("INSERT INTO sightings(user_id,species,scientific_name,category,description,photo_key,latitude,longitude,confidence) VALUES(?,?,?,?,?,?,?,?,?)").bind(me.id,b.species,b.scientificName||null,b.category||null,b.description||null,key,b.latitude??null,b.longitude??null,b.confidence??null).run();return J({ok:true,id:r.meta.last_row_id},201)}
if(u.pathname==="/api/identify"&&req.method==="POST"){if(!await user(req,env))return J({error:"Log eerst in om te scannen."},401);if(!env.OPENAI_API_KEY)return J({error:"AI-herkenning is nog niet geconfigureerd."},503);const {image}=await req.json();if(!image)return J({error:"Geen foto ontvangen"},400);const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:"Bearer "+env.OPENAI_API_KEY,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5-mini",input:[{role:"user",content:[{type:"input_text",text:"Identify the animal. Respond only as JSON: species (Dutch common name or null), scientificName, category, description (two short Dutch sentences), confidence (0-1). Never invent a species if uncertain."},{type:"input_image",image_url:image}]}]})});if(!r.ok)return J({error:"AI-herkenning mislukt"},502);const d=await r.json(),t=d.output?.flatMap(o=>o.content||[]).find(c=>c.type==="output_text")?.text||"";try{return J({animal:JSON.parse(t.replace(/^```json\s*|\s*```$/g,""))})}catch{return J({error:"Herkenningsservice gaf geen bruikbaar antwoord"},502)}}
return J({error:"Niet gevonden"},404)}catch(e){console.error(e);return J({error:"Serverfout"},500)}}};